### ISSUE TITLE
move as much code to napalm itself

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-ansible#100]
The plugin system of ansible is terrible, that's why ansible itself doesn't use it and their modules are basically intertwined in the codebase. The reason I am saying this is because it encourages duplicating a lot of code. For this reason, I was wondering if we should move as much code as possible to `napalm` itself so we don't have to repeat the same code over and over.

@ktbyers thoughts?

**Comment by ktbyers** [comment]
Yes, I think this is a good idea.

**Comment by targuan** [comment]
It may not be a good idea to "pollute" the core code with some ansible specific code.
If code duplication is your motive it may be a better idea to create an utility package and add it to the ansible's module_utils path.

**Comment by dbarrosop** [comment]
I don't think having `napalm.base.integrations.ansible` is that much of a deal, it's quite compartmentalized and shouldn't be a huge amount of code anyway. What I agree is that napalm drivers shouldn't need to know about ansible/salt/other but having some useful functions in an very well defined submodule should be fine. I am also ok with following your suggestion and creating `napalm-utils` repo for this sort of things. I guess that now we are getting rid of repos creating a new one feels odd XD

@ktbyers do you have any opinion? I personally don't mind either option.

**Comment by ktbyers** [comment]
@dbarrosop I would probably rather push the functions into `napalm.base.integrations.ansible`...my only concern is whether we are actually going to save much code.

My assumption is that we wouldn't have any Ansible libraries involved in these functions so I am not sure how much code savings we are going to achieve.

Or worded another way @targuan if we go the `module_utils` route can we achieve better modularity and code reuse?

**Comment by dbarrosop** [comment]
There is going to be very little code TBH, mostly code to deal with the imports and the arguments so the are consistent. Alternatively we could just have a file with the common code here and have a Makefile that appends the content of that file to all the modules.

**Comment by targuan** [comment]
I made a quick exemple with napalm_get_facts : https://github.com/targuan/napalm-ansible/tree/feature/module_utils
Generic code has been moved to module_utils directory.
I didn't look further, but it doesn't seems to be supported by ansible 2.2.

**Comment by dbarrosop** [comment]
yeah, I think it would be easier to do the same you are suggesting but doing the concatenation ourselves.

**Comment by ogenstad** [comment]
Given that napalm-ansible is it's own library I think it would be easier to contain the code in this repo.

Also there's a PR #72 to add action plugins. I don't really like the structure of that one. What I would propose is to move the modules current modules. So currently we have napalm_ansible/napalm_get_facts, a way forward could be to have

napalm_ansible/common.py
napalm_ansible/plugins/action/napalm_get_facts.py
napalm_ansible/modules/napalm_cli.py
napalm_ansible/modules/napalm_get_facts.py

This way you wouldn't have to release a new version of Napalm to change something related to Ansible, I think it would make life easier. The downside is that people upgrading would have to change the library path in ansible.cfg at some stage.

**Comment by dbarrosop** [comment]
I am not sure how action plugins work but if that help reusing code that'd be great. Also, your suggestion of having it here might be actually the best alternative.
