### ISSUE TITLE
virtualenv

### ISSUE THREAD

**Issue by johnsondnz** [napalm-automation/napalm-ansible#109]
without `ansible_python_interpreter` set napalm module cannot be found.  all other ansible modules work when a python virtualenv is `activate`.

python complains that module napalm cannot be found without the ansible_python_interpreter knob set.

**Comment by ktbyers** [comment]
In general you should always set `ansible_python_interpreter` otherwise you are probably not using the Python of your virtual environment (you are probably using /usr/bin/python if you don't set this...but I would have to double check what Ansible does here and if they have changed it recently).

So this is likely caused by not using your virtual environment Python due to lack of setting that variable and NAPALM is the missing from the Python that you are defaulting to (likely /usr/bin/python).

**Comment by FloLaco** [comment]
@johnsondnz @ktbyers In case of using virtualenv, what value should we use for `ansible_python_interpreter` ?

**Comment by lunixcz** [comment]
@FloLaco See https://github.com/napalm-automation/napalm-ansible/issues/64

I'm still unable to get napalm-ansible working with or without virtual env. Still getting:
  * test                   - FAILED!!! -- the python module napalm is required ------------

I'm using Debian Buster (testing), Ansible installed from distro, all other Ansible modules I've tried are working just fine.

I've added this line to ansible/group_vars/all.yaml:
ansible_python_interpreter: "/usr/bin/env python"

I'm trying to launch examples from https://github.com/dravetech/napalm-ansible-tutorial with modified host file.

**Comment by ktbyers** [comment]
@lunixcz Which Python is ansible installed into? Which python is napalm installed into? They really need to be/should be the same Python

Please use `python -m pip list` and print out the packages installed on that system for the relevant Python.

**Comment by lunixcz** [comment]
@ktbyers Thank you for pointing me in that direction. Really the distro Ansible was Python 2 and I had Napalm installed for Python3. I've removed the distro Ansible and installed it with pip3, now both are installed in Python3. Unfortunately I'm still getting the same error.

$ python3 -m pip list | grep ansible
ansible             2.7.9    
napalm-ansible      0.10.0   
$ python3 -m pip list | grep napalm
napalm              2.4.0    
napalm-ansible      0.10.0   

Checking if the pip3 ansible binary is really used:
$ which ansible-playbook
/usr/local/bin/ansible-playbook

I run this on freshly cloned tutorial, without venv as in venv I cannot install the packages already present in the system. I've adjusted the library path in ansible.cfg (but getting the same result for both options):
#library = napalm-ansible/library
library = /usr/local/lib/python3.7/dist-packages

~/napalm-test/napalm-ansible-tutorial/ansible$ ansible-playbook playbook_hello_world.yaml
# get facts from device ***************************************************************************************************
  * rtr01                      - FAILED!!! -- the python module napalm is required ------------
  * rtr00                      - FAILED!!! -- the python module napalm is required ------------
  * rtr02                      - FAILED!!! -- the python module napalm is required ------------
	to retry, use: --limit @/home/lunix/napalm-test/napalm-ansible-tutorial/ansible/playbook_hello_world.retry

I'm installing the pip3 packages on system level:
# pip3 install ansible
Requirement already satisfied: ansible in /usr/local/lib/python3.7/dist-packages (2.7.9)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from ansible) (2.10)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from ansible) (40.8.0)
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (from ansible) (2.4.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible) (2.3)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from ansible) (3.13)

# pip3 install napalm-ansible
Requirement already satisfied: napalm-ansible in /usr/local/lib/python3.7/dist-packages (0.10.0)
Requirement already satisfied: napalm in /usr/local/lib/python3.7/dist-packages (from napalm-ansible) (2.4.0)
Requirement already satisfied: netmiko>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (2.3.3)
Requirement already satisfied: cffi>=1.11.3 in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (1.12.2)
Requirement already satisfied: textfsm in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (0.4.1)
Requirement already satisfied: pyYAML in /usr/lib/python3/dist-packages (from napalm->napalm-ansible) (3.13)
Requirement already satisfied: netaddr in /usr/lib/python3/dist-packages (from napalm->napalm-ansible) (0.7.19)
Requirement already satisfied: junos-eznc>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (2.2.0)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from napalm->napalm-ansible) (2.10)
Requirement already satisfied: nxapi-plumbing>=0.5.2 in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (0.5.2)
Requirement already satisfied: scp in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (0.13.2)
Requirement already satisfied: setuptools>=38.4.0 in /usr/lib/python3/dist-packages (from napalm->napalm-ansible) (40.8.0)
Requirement already satisfied: paramiko>=2.4.2 in /usr/lib/python3/dist-packages (from napalm->napalm-ansible) (2.4.2)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (0.17.1)
Requirement already satisfied: pyeapi>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (0.8.2)
Requirement already satisfied: pyIOSXR>=0.53 in /usr/local/lib/python3.7/dist-packages (from napalm->napalm-ansible) (0.53)
Requirement already satisfied: pyserial in /usr/local/lib/python3.7/dist-packages (from netmiko>=2.3.0->napalm->napalm-ansible) (3.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.11.3->napalm->napalm-ansible) (2.19)
Requirement already satisfied: lxml>=3.2.4 in /usr/local/lib/python3.7/dist-packages (from junos-eznc>=2.2.0->napalm->napalm-ansible) (4.3.2)
Requirement already satisfied: ncclient>=0.5.4 in /usr/local/lib/python3.7/dist-packages (from junos-eznc>=2.2.0->napalm->napalm-ansible) (0.6.3)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from junos-eznc>=2.2.0->napalm->napalm-ansible) (1.12.0)
Requirement already satisfied: requests>=2.7.0 in /usr/lib/python3/dist-packages (from nxapi-plumbing>=0.5.2->napalm->napalm-ansible) (2.21.0)
Requirement already satisfied: selectors2>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from ncclient>=0.5.4->junos-eznc>=2.2.0->napalm->napalm-ansible) (2.0.1)

The -vvvv output is here:
https://storage.lunix.cz/tmp/napalm

I would be gratefull for any other clues.

**Comment by FloLaco** [comment]
Does your /usr/bin/env python point out to the version 3 ?
What about python --version ?

**Comment by lunixcz** [comment]
Guys, excuse me for being Python lame. My default python was version 2 and I had all modules installed under version 3. This has fixed it in Debian Buster for me:

rm /usr/bin/python
ln -s /usr/bin/python3 /usr/bin/python

I hope this will help somebody else as well.

To sum it up, to use Napalm + Ansible under Python3:
All involved modules (napalm, ansible, napalm-ansible, and dependencies) must be listed here:
python3 -m pip list
Python version must match as well:
python --version 
/usr/bin/env python --version

It works now. Thanks!

**Comment by ktbyers** [comment]
I suspect you also could have set this in your ansible inventory (for the hosts that are using napalm):

```
ansible_python_interpreter=/path/to/relevant/python
```
