### ISSUE TITLE
Extend a driver and reference it with napalm-ansible

### ISSUE THREAD

**Issue by radtrentasei** [napalm-automation/napalm-ansible#115]
Dear napalm developers,
 
It is not clear to me how to reference a custom method deployed for a network driver into the napalm-ansible module.
 
Reading the documentation : http://napalm.readthedocs.io/en/latest/tutorials/extend_driver.html it is stated
 
‘The positive side effect is that tools such as Salt, Ansible, and Netbox implicitly have access to these methods.’
 
So far what I was able to obtain is to leverage my method (get_service_policies) from a standard python script. I have created in the script working directory the custom_napalm folder with the ios.py file and I have expanded the IOSDriver class.
 
To my understanding I have to write an ansible task as this: 
 
- name: get facts from device
  napalm_get_facts:
    hostname={{ ansible_host }}
    username={{ ansible_user }}
    dev_os={{ os }}
    password={{ ansible_password }}
    filter='service_policies'
  register: result
 
 
I believe I have to move this folder somewhere else in order to be visible from the ansible module. Can you clarify ?

**Comment by dbarrosop** [comment]
This is the code relevant for you:

```
    NAPALM_GETTERS = [getter for getter in dir(network_driver) if getter.startswith("get_")]

    for getter in filter_list:
        getter_function = "get_{}".format(getter)
        if getter_function not in NAPALM_GETTERS:
            module.fail_json(msg="filter not recognized: " + getter)
```

Which means if you call your method `get_my_custom_method` you can just reference it by putting in the `filters = ["my_custom_method"]`

I am closing this issue as there is nothing to do, feel free to reopen or comment if needed.

**Comment by radtrentasei** [comment]
Hello David,

thank you for your prompt reply; unfortunately I still have some doubts . 

My concern is on where to create the custom_napalm folder in order to be visible from napalm_get_facts.py .

Naming convention is clear. I have tried to add the method to the ios.py in napalm/ios and I am able to refer it from the ansible module.

**Comment by dbarrosop** [comment]
That's a broader issue not related to ansible or the ansible modules but if you are extending a driver I'd suggest first making sure you can use that directly from python and then take it from there. I'd also suggest taking this in the main `napalm` repo as there is other people that could help there as well on this topic.
