### ISSUE TITLE
Does napalm-ansible support network_cli

### ISSUE THREAD

**Issue by netixx** [napalm-automation/napalm-ansible#124]
Does the modules provided by napalm-ansible support [network_cli](http://docs.ansible.com/ansible/2.5/plugins/connection/network_cli.html) connection plugin provided by ansible (recommended in 2.5) ?

This would allow pipelining and avoid providing connection parameters such as "dev_os".

**Comment by dbarrosop** [comment]
AFAICT third party plugins can't take advantage of those things.

**Comment by dbarrosop** [comment]
Also, napalm tries to use APIs whenever possible so pipelining is not always relevant.

Closing the issue for now but feel free to reopen if you think there is something to be done.

**Comment by ktbyers** [comment]
No we don't support network_cli, NAPALM inherently depends on the underlying transport mechanisms integrated into the code.

It is pretty unlikely we would support network_cli since we inherently support many distinct platforms (Salt, StackStorm, Ansible, Brigade, straight Python).

**Comment by netixx** [comment]
Thank you for your answer.

I see in the recent updates that you use the ansible connection variables (username, password). Ansible now has "ansible_network_os" variable, do you support this as well (in place of napalm's dev_os) ?

**Comment by dbarrosop** [comment]
Not yet supported but feel free to send a PR adding support for it :)

Thanks!
