### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by vincentbernat** [napalm-automation/napalm-ansible#175]
Since 1.0.0, napalm-ansible is now able to get `dev_os`, `username` and `password` from the appropriate Ansible variables. It would be useful to craft a new release to get this feature.

Thanks.

**Comment by ktbyers** [comment]
@vincentbernat Sounds good on doing a new release. I will try to do one next week (if I can).

I actually think all of those items you mentioned are in napalm-ansible 1.0.0 (though I think Ansible 2.9 broke some things in napalm-ansible 1.0 so worth a new release for that).

Probably should move to collection format after this release.

**Comment by ktbyers** [comment]
Looking at the commit history some more looks like there was a `-u username` fix since the last release also.

Anyways a new release is needed.

**Comment by vincentbernat** [comment]
Thanks! The collection format would have been my next question. Glad to know the conversion is planned as well.

**Comment by ktbyers** [comment]
Done:

https://github.com/napalm-automation/napalm-ansible/releases/tag/1.1.0
