### ISSUE TITLE
Distribute napalm-ansible as a collection

### ISSUE THREAD

**Issue by targuan** [napalm-automation/napalm-ansible#178]
Hello,

It could ease the installation of napalm-ansible if it was released as a collection in galaxy.

If installed as a collection, there is no need to update the ansible.cfg for the modules to be used, napalm-ansible can be used as a dependancy of a project and in awx.

To use it as a collection, it need to have a namespace and a collection name (for instance napalm-automation.napalm) and the module can be used with the fqdn napalm-automation.napalm.napalm_install_config.

In order to keep the current usage, it could still be distributed through pip.

**Comment by ktbyers** [comment]
Yes, sounds good. We should definitely do this. I am not sure I am going to get to it before September, however.

If you want to work on that would be good also.

It would be good if in Ansible Galaxy it would be in a more generic bucket like `napalm-automation.napalm` (in other words so it wasn't bound to one persons account and multiple people can update it). I can probably see if I can create the `napalm-automation` account in Galaxy.

Just let me know if you want to work on this? If so, I will create the Galaxy account we can store this under.

**Comment by targuan** [comment]
I can work on that.

I think that for a Github org namaspace, you have to open an issue on their [github ](https://github.com/ansible/galaxy/issues/new?assignees=gundalow&labels=area%2Fnamespace&template=New_namespace.md&title=namespace%3A+FIXME)

**Comment by targuan** [comment]
I am currently working on the implementation.

The structure for the python library package and the ansible collection are quite different. I don't think it would be possible to have a common strcture.
Should we keep the python package ?
Ansible 2.8 is still under security maintenance and does not support collections. If we want to keep the support for this version we still need to create a pip package.
Ansible 2.10 allows to pull a collection directly from a git repository but the structure has to be changed.

**Comment by ktbyers** [comment]
Yes, let's keep this Python package and create something new for the Collection. 

Given the significant changes for Ansible 2.10, Ansible 2.9 is going to be around for a good chunk of time in the field.

**Comment by ktbyers** [comment]
Took awhile...but finally got this done.

https://galaxy.ansible.com/napalm/napalm
