### ISSUE TITLE
napalm-ansible ignoring ProxyCommand

### ISSUE THREAD

**Issue by tars01** [napalm-automation/napalm-ansible#181]
I am trying to use napalm-ansible via a Jump Host using the ssh ProxyCommand but it seems to totally ignore the ssh_common_args.

I have this setup working with standard ansible playbooks and it connects via the Jump Host and everything functions correctly. The way it's setup for ansible is having the ProxyCommand entry in the /group_vars/group.yaml file:

`ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q user@10.0.10.100"'`

When I run an napalm-ansible playbook it complete ignores the ansible_ssh_common_args variable and it tries to connect directly to the end device/s which are in the inventory file. I have also put the above ProxyCommand var statement in the napalm-ansible inventory file but it doesn't work either. If I put a device in the inventory file that is directly accessible (doesn't need to go via the Jump Host) everything works fine so napalm-ansible is functioning fine.

Does the ProxyCommand need to be configured differently for the ansible-napalm playbooks?

Thanks

**Comment by ktbyers** [comment]
NAPALM-ansible supports Netmiko format for this for ios, and nxos_ssh platforms.

https://github.com/ktbyers/netmiko/blob/develop/EXAMPLES.md#ssh-config-file

Junos would probably be PyEZ mechanisms on this.

IOS-XR, I am unsure whether it has properly wired in Netmiko for this.

Arista is an HTTPS API so it wouldn't support this.


Regards, Kirk

**Comment by tars01** [comment]
Thanks I will give that a try.
