### ISSUE TITLE
Argument `filter` in napalm_get_facts is not a list

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-ansible#21]
Despite the documentation claiming that is a `list` the `filter` argument is in fact a string. It turns out you can pass a comma separated list of filters but it's not clear in the documentation and it's very fragile as `facts,bgp_neighbors` will work but `facts, bgp_neighbors` will not. Why not make it a real list instead?

**Comment by fooelisa** [comment]
I made it a list, but it seems that the way lists are used in playbooks is still pretty fragile (eg.spaces will still break). #24

**Comment by dbarrosop** [comment]
I don't understand what you mean. You don't use spaces to define lists in `yaml`.

**Comment by fooelisa** [comment]
Hm right, I guess have to adhere to yaml list formatting then... never mind me :) this is fixed
