### ISSUE TITLE
Testing NAPALM

### ISSUE THREAD

**Issue by RichardBotham** [napalm-automation/napalm-ansible#32]
Hi All,

I've been trying to test napalm with the following setup and keep getting the error as shown below.

update: I also tested connectivity

```
[rbotham@ernie napalmpb]$ sh conn_napalm.sh 
Successfully connected to the device.
[rbotham@ernie napalmpb]$ 

```

Any assistance would be a great help

versions below

[rbotham@ernie napalmpb]$ ansible --version
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

[rbotham@ernie napalmpb]$ python --version
Python 2.7.8

napalm (1.1.0)
napalm-base (0.15.0)
napalm-eos (0.3.0)
napalm-fortios (0.1.1)
napalm-ibm (0.1.1)
napalm-ios (0.2.0)
napalm-iosxr (0.2.2)
napalm-junos (0.3.0)
napalm-nxos (0.3.0)
napalm-panos (0.1.0)
napalm-pluribus (0.3.0)

[rbotham@ernie napalmpb]$ ansible --version
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

host file contents below

[junos]
junipervm3

test_napalm2.yml file contents below

``````

---

- name: Test NAPALM on JUNOS
  hosts: junos

  tasks:
    - name: Test Napalm on Junos
      napalm_install_config:
            hostname: junipervm3
            username: rich
            password: password
            config_file: new_config.conf


```Error
[rbotham@ernie napalmpb]$ ansible-playbook test_napalm2.yml -i ../../ansible-hosts 
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/rbotham/playbooks/playbookdb/napalmpb/test_napalm2.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Test Napalm on Junos
      ^ here


The error appears to have been in '/home/rbotham/playbooks/playbookdb/napalmpb/test_napalm2.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Test Napalm on Junos
      ^ here
``````

**Comment by ktbyers** [comment]
@RichardBotham Do you have napalm_install_config in your Ansible module path?

```
ansible-playbook napalm2_ios.yml -M ~/napalm-ansible/library/
```

**Comment by RichardBotham** [comment]
Is that here
`#library        = /usr/lib/python2.7/site-packages/napalm_base`
or here
`# default module name for /usr/bin/ansible
#module_name = command`
or somewhere else that i haven't looked :)

I do apologize, i have read all the articles you and Dave put up on what to check first but i'm stuck as i couldn't find an awful lot of real detail on Ansible module path

**Comment by dbarrosop** [comment]
Check this repo as an example:

https://github.com/dravetech/preso_abstract_all_the_things/tree/master/ansible

You will need a folder where to put your modules (`library` folder on that example) and then tell ansible you have modules stored there:

https://github.com/dravetech/preso_abstract_all_the_things/blob/master/ansible/ansible.cfg

**Comment by dbarrosop** [comment]
I am not sure that's your issue though. This is a bit weird:

```
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'
```

I think your issue might be that you are missing this:

```
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
```

Check this as an example: https://github.com/dravetech/preso_abstract_all_the_things/blob/master/ansible/deploy_network.yml

**Comment by RichardBotham** [comment]
Dave, 
Appreciate your help
OK so i tried that with no luck

Also a bit confused about how to 'find' the napalm modules.
I installed napalm as per the instructions but as Kirk said "Do you have napalm_install_config in your Ansible module path?"

I was using an educated guess that `/usr/bin/python2.7/site-packages` would be where to look for the modules - I'm obviously wrong

```
[rbotham@ernie napalmpb]$ pip show napalm
---
Name: napalm
Version: 1.1.0
Location: /usr/lib/python2.7/site-packages
Requires: napalm-base, napalm-eos, napalm-fortios, napalm-ibm, napalm-ios, napalm-iosxr, napalm-junos, napalm-nxos, napalm-pluribus, napalm-panos
[rbotham@ernie napalmpb]$ 

Name: ansible
Version: 2.1.1.0
Location: /usr/lib/python2.7/site-packages
Requires: paramiko, jinja2, PyYAML, setuptools, pycrypto
```

Have i missed something fundamental about the install of napalm ?

```
[defaults]

# some basic default values...

#inventory      = /home/rbotham/playbooks/ansible-hosts
#library        = /usr/lib/python2.7/site-packages/napalm_base
```

Anything else i should check

```
[rbotham@ernie napalmpb]$ cat test_napalm2.yml 
---

- name: Test NAPALM on JUNOS
  hosts: junks
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: Test Napalm on Junos
      napalm_install_config:
            hostname: junipervm3
            username: rich
            password: password
            dev_os: junks
            config_file: new_config.conf
            commit_changes: False
            replace_config: True


[rbotham@ernie napalmpb]$ ansible-playbook test_napalm2.yml -i ../../ansible-hosts 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/rbotham/playbooks/playbookdb/napalmpb/test_napalm2.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Test Napalm on Junos
      ^ here


The error appears to have been in '/home/rbotham/playbooks/playbookdb/napalmpb/test_napalm2.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Test Napalm on Junos
      ^ here
```

**Comment by GGabriele** [comment]
Can you do a quick test? Create a dir called `library` on your working directory and place a copy of `napalm_install_config.py` there, then try to re-run the playbook.

Does it show the same error?

**Comment by dbarrosop** [comment]
ansible modules are not installed automatically. The easiest way to do it is as follows:

```
cd /path/to/somewhere/
git clone https://github.com/napalm-automation/napalm-ansible.git
```

Then, make sure your library points there.

**Comment by ktbyers** [comment]
@RichardBotham I am pretty sure your issue is just the lack of pointing to the library (as I saw the same error when I didn't specify the module path):

So do what David mentions above:

```
cd /path/to/somewhere/
git clone https://github.com/napalm-automation/napalm-ansible
```

Then point to the napalm-ansible library

```
ansible-playbook my_playbook.yml -M /path/to/somewhere/napalm-ansible/library
```

**Comment by eegilbert** [comment]
I ended up here because I am having a similar issue. When doing this step, you also need to set up the library path in ansible.cfg or as an environment variable:

`sudo ansible-galaxy install -r requirements.yaml --force`

`- src: https://github.com/napalm-automation/napalm-ansible/
  version: master
  name: napalm
  path: roles`

/etc/ansible/ansible.cfg
`library        = /etc/ansible/roles`

This seems redundant and possible conflicting. I'm not enough of an ansible guru to know what consequences have library and roles being the same path is. Would it make more sense to have the path statement in requirements.yaml point to a different place?

Different topic, how are we supposed to supply the enable password? I've tried secret='pass' and enable_secret='pass' and neither seems to work.

`TASK [Get Facts] ***************************************************************
fatal: [switch0]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: enable_secret"}`

I can use the cl_napalm_test with the following:

`cl_napalm_test --vendor ios --user user --password 'pass' --optional_args 'secret=pass' 10.1.0.2`

and I get a success message

So the question becomes how to pass optional_args in the manifest?

Thank you!

**Comment by dbarrosop** [comment]
Regarding galaxy, don't use it. We should update the README to remove those instructrions. Just download the modules to your library folder.

Regarding secret, just pass an `optional_args` value with the optional arguments you want as a dictionary:

```
napalm_install_config:
   hostname: ads
   ...
   optional_args:
       my_opt1: qwe
```

**Comment by dbarrosop** [comment]
By the way, closing this issue as we haven't heard anything since last comment from Kirk some months ago.

Feel free to reopen if you still need help.
