### ISSUE TITLE
Support enable mode and passing in of secret argument

### ISSUE THREAD

**Issue by nickermire** [napalm-automation/napalm-ansible#35]
I'm also having this problem when calling napalm via Ansible. Had to set privilege mode of user to 15 in order to get this module to work. 

Also have to delete the secret variable as it breaks the playbook.

Netmiko version is 1.1.0.

Here is my playbook.yml
` - name: Push config to switch group.
hosts: test 
connection: local
gather_facts: no

tasks:
- name: get facts from device
napalm_get_facts:
hostname={{ inventory_hostname }}
username=theusername
dev_os=ios
password=thepassword
secret=thesecret
filter='interfaces'
register: result

- debug: msg= "{{ result.stdout }}"`

**Comment by ktbyers** [comment]
@nickermire You need to pass 'secret' into ansible as an 'optional_args':

```
optional_args: {'secret': thesecret}
```

**Comment by nickermire** [comment]
I've tried putting it in, but it doesn't take. I get syntax errors about the other variables depending upon where I put it under napalm_get_facts:

name: get facts from device
napalm_get_facts:
hostname={{ inventory_hostname }}
username=theusername
dev_os=ios
password=thepassword
**optional_args: {'secret': thesecret}**
filter='interfaces'
register: result

**Comment by ktbyers** [comment]
@nickermire Please post the error you see when trying to execute your playbook.

**Comment by nickermire** [comment]
ERROR! Syntax Error while loading YAML.

The error appears to have been in
'/home/user/ansible/Conf-Auto/napalm.yml': line 18, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

```
    hostname={{ inventory_hostname }}
    username=theuser
    ^ here
```

**Comment by ktbyers** [comment]
@nickermire Post your full playbook enclose it in triple backticks so that it doesn't get modified by the markdown.

Remove/hide anything that is confidential.

```
Use these
```

```
It will show up like this
```

**Comment by nickermire** [comment]
```
---
- name: Push config test to switch group.
  hosts: test 
  connection: local
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        optional_args={'secret': thesecret}
        hostname={{ inventory_hostname }}
        username=theusername
        dev_os=ios
        password=thepassword
        filter='interfaces'
      register: result


    - debug: msg= "{{ result.stdout }}"
```

**Comment by ktbyers** [comment]
@nickermire I would try it using Ansible's other argument format (which is standard YAML). Note the format is now using a colon (i.e. key: value format)

This is only the tasks section:

``` tasks:
    - name: get facts from device
      napalm_get_facts:
        optional_args: {'secret': thesecret}
        hostname: "{{ inventory_hostname }}"        # You probably need double quotes here
        username: theusername
        dev_os: ios
        password: thepassword
        filter: 'interfaces'
      register: result
```

Try this and let me know what you see.

**Comment by nickermire** [comment]
```
---
- name: Push config to switch group.
  hosts: test
  connection: local
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        optional_args: {'secret': thesecret}
        hostname: "{{ inventory_hostname }}"
        username: theusername
        dev_os: ios
        password: thepassword
        filter: 'interfaces'
      register: result

    - debug: msg= "{{ result.stdout }}"
```

The output below looks to me like the enable attribute has still not been passed through as SITE-AS-01 was successful (account had 15 privileges on that switch) and the others were not. Also looks like I may have the debug command syntax wrong now after the colon changes.

PLAY [Push config to switch group.] ********************************************

TASK [get facts from device] ***************************************************
fatal: [SITE-AS-02]: FAILED! => {"changed": false, "failed": true, "msg": "cannot connect to device: An error occurred in dynamically determining remote file system: dir % Unknown command or computer name, or unable to find computer address"}
fatal: [SITE-AS-03]: FAILED! => {"changed": false, "failed": true, "msg": "cannot connect to device: An error occurred in dynamically determining remote file system: dir % Unknown command or computer name, or unable to find computer address"}
fatal: [SITE-AS-04]: FAILED! => {"changed": false, "failed": true, "msg": "cannot connect to device: An error occurred in dynamically determining remote file system: dir % Unknown command or computer name, or unable to find computer address"}
ok: [SITE-AS-01]

TASK [debug] *******************************************************************
fatal: [SITE-AS-01]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/home/user/ansible/Conf-Auto/napalm.yml': line 25, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg= \"{{ result.stdout }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'napalm.retry'.         [Errno 2] No such file or directory: ''

PLAY RECAP *********************************************************************
SITE-AS-01                  : ok=1    changed=0    unreachable=0    failed=1  
SITE-AS-02                  : ok=0    changed=0    unreachable=0    failed=1  
SITE-AS-03                  : ok=0    changed=0    unreachable=0    failed=1  
SITE-AS-04                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by nickermire** [comment]
```
task path: /home/username/ansible/Conf-Auto/napalm.yml:14
<192.168.1.2> ESTABLISH LOCAL CONNECTION FOR USER: username
<192.168.1.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478093064.79-211049188987974 `" && echo ansible-tmp-1478093064.79-211049188987974="` echo $HOME/.ansible/tmp/ansible-tmp-1478093064.79-211049188987974 `" ) && sleep 0'
<192.168.1.2> PUT /tmp/tmpGjzG4A TO /home/username/.ansible/tmp/ansible-tmp-1478093064.79-211049188987974/napalm_get_facts
<192.168.1.2> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1478093064.79-211049188987974/napalm_get_facts; rm -rf "/home/username/.ansible/tmp/ansible-tmp-1478093064.79-211049188987974/" > /dev/null 2>&1 && sleep 0'
fatal: [SITE-AS-02]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dev_os": "ios", "filter": ["interfaces"], "hostname": "SITE-AS-02", "optional_args": {"secret": "thesecret"}, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "timeout": 60, "username": "theuser"}, "module_name": "napalm_get_facts"}, "msg": "cannot connect to device: An error occurred in dynamically determining remote file system: dir % Unknown command or computer name, or unable to find computer address"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'napalm.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
SITE-AS-02                  : ok=0    changed=0    unreachable=0    failed=1   

```

**Comment by ktbyers** [comment]
See https://github.com/napalm-automation/napalm-ios/issues/63

**Comment by nickermire** [comment]
Added those to lines of code for the change referenced above. I'm still having the same error as displayed above.

```
+        # ensure in enable mode
+        self.device.enable()
```

**Comment by ktbyers** [comment]
@nickermire This fixed the above issue for me.

Are you sure Ansible is using the new napalm-ios i.e. did you 'python setup.py install' the new napalm-ios?

Also, you are probably going to need to take this out of napalm-ansible and test straight in napalm.

Here is a sample test script:

```
#!/usr/bin/env python
from getpass import getpass
from pprint import pprint as pp

from napalm_base import get_network_driver
import napalm_ios
from netmiko import ConnectHandler


ip_addr = '1.1.1.1'
username = 'test9'
password = getpass()
optional_args = {}
optional_args['secret'] = password

driver = get_network_driver('ios')
device = driver(ip_addr, username, password, optional_args=optional_args)

print
print(">>>Test device open")
print(device)
device.open()

print device.dest_file_system

print
print(">>>Test get facts")
device_facts = device.get_facts()
pp(device_facts)
```

This works for me using an account that requires an enable secret.

**Comment by nickermire** [comment]
Thank you for the quick reply. I have successfully executed the above
script. Not sure where to look in Ansible to fix this. Again thanks for
your time.

**Comment by dbarrosop** [comment]
Sorry to jump in without reading the entire thread. This might look obvious but... are you using a virtualenv? Are you sure ansible is using the same virtualenv you are using when testing with the sample script @ktbyers gave you?

**Comment by ktbyers** [comment]
@dbarrosop @nickermire Yes, I would start with what David is recommending i.e. make sure that the python that napalm-ansible is using has the right version of napalm-base and napalm-ios.

**Comment by nickermire** [comment]
I'm still pretty new to applying this to anything real. I do not have a
virtualenv setup separately. I installed this on a Ubuntu 16.10 box with
pip install napalm and apt-get install ansible. Then after Kirk added that
line of code, I simply added it in the same place in my pip napalm_ios
install directory (
/home/username/.local/lib/python2.7/site-packages/napalm_ios/ios.py. Then
deleted the **init**.pyc and ios.pyc files within directory napalm_ios
directory and re-ran the code.

Hope this is the information you both are asking for.

Again, thank you for your help.

Nick Stevermer

**Comment by ktbyers** [comment]
@nickermire I didn't see any issue with this when I tested it:

```
$ cat test_ios.yml 
---
- name: NAPALM gather information on IOS
  hosts: pynet-rtr1
  tasks:
    - name: Gather information
      napalm_get_facts:
        hostname: "{{ host }}"
        username: test9
        password: "{{ password }}"
        optional_args: {'secret': 'secret'}
        dev_os: ios
        filter: [facts, interfaces, bgp_neighbors]
      register: result
      tags: facts

    - name: Debuggging
      debug: var=result
      tags: facts
```

**Comment by ktbyers** [comment]
And here was my install process + verification.

```
$ git clone https://github.com/napalm-automation/napalm-ios
Cloning into 'napalm-ios'...
remote: Counting objects: 1260, done.
remote: Total 1260 (delta 0), reused 0 (delta 0), pack-reused 1260
Receiving objects: 100% (1260/1260), 235.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (549/549), done.
Checking connectivity... done.

[ip-172-30-0-8 ~]$ cd napalm-ios/
[ip-172-30-0-8 napalm-ios]$ python setup.py install
...

$ cd ~
$ which python
~/applied_python/bin/python
$ python
>>> import napalm_ios
>>> napalm_ios.__version__
'0.3.1'
```

**Comment by dbarrosop** [comment]
@nickermire is this still an issue?

**Comment by ktbyers** [comment]
I am just going to close this...open it if you still have issues.

I tested it and saw no issue both at Python level and using Ansible.

**Comment by nickermire** [comment]
I still get the below output. I reinstalled napalm per ktbyers' directions above.

```
user@ansi:~/ansible/Conf-Auto$ ansible-playbook napalm.yml 

PLAY [Push config to switch group.] ********************************************

TASK [get facts from device] ***************************************************
fatal: [SITE-SW-01]: FAILED! => {"changed": false, "failed": true, "msg": "cannot connect to device: Timed-out reading channel, data not available."}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'napalm.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
SITE-SW-01                 : ok=0    changed=0    unreachable=0    failed=1   

```
```
---
- name: Push config to switch group.
  hosts: test 
  connection: local
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        optional_args: {'secret': thesecret}
        hostname: "{{ inventory_hostname }}"
        username: theuser
        dev_os: ios
        password: thepassword
        filter: 'interfaces'
      register: result
      
    - debug: var=result verbosity=2

```

```
#which python
/usr/bin/python
#python -V
Python 2.7.12+
#cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"

```

**Comment by ktbyers** [comment]
@nickermire But if you run the NAPALM Python script at the top it still works?

Is there anything unusual about this device--is it really slow to login? Are you using TACACS+?

Just trying to figure out what is different.

Also please print out your napalm_ios and napalm_base version:

```
>>> import napalm_base
>>> import napalm_ios
>>> napalm_ios.__version__
'0.3.1'
>>> napalm_base.__version__
'0.19.1'
```

Your numbers might not match the above, but I want to see what they are.

**Comment by nickermire** [comment]
No TACACS+, switch is a standard 2960x 48 port. The NAPALM python script above did indeed work. 

```
>>> import napalm_base
>>> import napalm_ios
>>> napalm_ios.__version__
'0.3.1'
>>> napalm_base.__version__
'0.18.0'
>>> 
```

**Comment by nickermire** [comment]
Hi All,

I had to add in connection: local and everything worked. I'm not sure why, but then again I'm still learning Ansible. Thank you all for such great support and hard work on an awesome project!

```
---
- name: NAPALM gather information on IOS
  hosts: testhost
  connection: local
  tasks:
    - name: Gather information
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: theusername
        password: thepassword
        optional_args: {'secret': 'thesecret'}
        dev_os: ios
        filter: [facts, interfaces, bgp_neighbors]
      register: result
      tags: facts

    - name: Debuggging
      debug: var=result
      tags: facts
```

**Comment by dbarrosop** [comment]
Glad you fixed it : )
