### ISSUE TITLE
napalm_install_config module: Privilege Denied w/enable Optl Argu

### ISSUE THREAD

**Issue by nickermire** [napalm-automation/napalm-ansible#39]
When trying to use the enable optional argument, this is what I get. However, if I go to the switch and set my privilege to 15 I do not get this error and my command is playbook is accepted. Does anybody have insight on to what I may be running into?

```
fatal: [SW-AS-07]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"commit_changes": true, "config_file": "test/running.conf", "dev_os": "ios", "diff_file": "test/initial.diff", "get_diffs": true, "hostname": "SW-AS-07", "optional_args": {"secret": "thesecret"}, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "replace_config": false, "timeout": 60, "username": "theuser"}, "module_name": "napalm_install_config"}, "msg": "cannot load config: Privilege denied.\n"}
```
```
---
- name: Change hostname test
  hosts: SW-AS
  connection: local
  tasks:

    - assemble:
        src: test/
        dest: test/running.conf

    - napalm_install_config:
        hostname: "{{ inventory_hostname }}"
        username: theuser
        password: thepassword
        optional_args: {'secret': 'thesecret'}
        dev_os: ios
        config_file: test/running.conf
        commit_changes: True
        replace_config: False
        get_diffs: True
        diff_file: test/initial.diff
      register: result

    - name: Debugging
      debug: var=result
```
running.conf
```
hostname test
```

**Comment by ktbyers** [comment]
@nickermire Yes, secret doesn't work for config operations.

The config operations use a Secure Copy channel and I am not aware of any way to have this SCP channel escalate its privileges (i.e. do "enable"). If you have a solution for this, let me know.

The issue is documented here:
https://github.com/napalm-automation/napalm-ios/issues/63

**Comment by b2sweety** [comment]
Hi, 
I am facing the same issue with ios device. When I run my playbook to generate a difference file i get below error:
fatal: [Device1]: FAILED! => {"changed": false, "failed": true, "msg": "cannot load config: Privilege denied.\n"}

Playbook: 
---
- hosts: Device1
  gather_facts: No
  connection: local

  tasks:
  - name: "Generate a Difference File"
    napalm_install_config:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      dev_os: "ios"
      config_file: ce1backup.conf
      commit_changes: False
      replace_config: True
      diff_file: initial.diff

The running-config contains these: 

!
enable secret 5 $1$AZBr$9HDw/F/pL3.CwFu0IRf3F0
!
!
aaa group server tacacs+ CIO
 server-private xx.xx.xx.xxx key 7 1234634087E0048CA23AC215D54
 server-private xx.xx.xx.xx key 7 123412341123351E43ABCD123
 server-private xx.xx.x.xx key 7 12345ABCD25123ABCD1235
 ip vrf forwarding CIO
 ip tacacs source-interface Loopback0
!

username local privilege 15 secret 5 52vFvX.pyacdb3aB/
!
line con 0
 privilege level 15
 logging synchronous
 stopbits 1
line aux 0
 stopbits 1
line vty 0 4
 privilege level 15
 password 7 0207B64C19161A02
 logging synchronous
 transport preferred none
 transport input ssh
 transport output telnet ssh
!
!

I am new to this and just trying to understand what could be the issue. Please help!

**Comment by ktbyers** [comment]
@b2sweety Try:

```
# Note this is just the task section of the playbook
- name: "Generate a Difference File"
  napalm_install_config:
  hostname: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  dev_os: "ios"
  config_file: ce1backup.conf
  commit_changes: False
  replace_config: True
  diff_file: initial.diff
  optional_args:
      inline_transfer: True
      # You must be at a privilege level that allows changes to running config
      secret: "{{ my_secret }}"
```
