### ISSUE TITLE
napam-ansible: config replace not working ( candidate.txt "%The input file is not a valid config file")

### ISSUE THREAD

**Issue by bleishangthem** [napalm-automation/napalm-ansible#54]
Hi All
Need help with this issue. A similar issues  #209 was  opened in the past. It is closed but i am not sure whether a fix is available. 

**_Problem: candidate.txt file created for config replace operation with ansible napalm module is considered not  valid by c6k ios  12.2(33)SXJ4,_** 

Here are the files created on the router after executing the playbook.

CAT6KLAB05#dir
Directory of sup-bootdisk:/
    1  -rw-   143315812  Mar 19 2017 13:05:24 +00:00  s72033-advipservicesk9_wan-mz.122-33.SXJ4.bin
  --snip----
   10  -rw-          21  Apr 29 2017 14:09:18 +00:00  candidate.txt
    5  -rw-           0  Apr 29 2017 14:05:58 +00:00  merge_config.txt
  --snip----
   17  -rw-        6268  Apr 29 2017 14:09:30 +00:00  rollback_config.txt
  --snip----
   13  -rw-        6250  Apr 29 2017 05:08:20 +00:00  ArchiveCfg-Apr-29-05-08-20.040-8318

CAT6KLAB05#  configure replace sup-bootdisk:candidate.txt
This will apply all necessary additions and deletions
to replace the current running configuration with the
contents of the specified configuration file, which is
assumed to be a complete configuration, not a partial
configuration. Enter Y if you are sure you want to proceed. ? [no]: Y

**%The input file is not a valid config file.**

--------------------------------------------------------
Here is my playbook.

 - name: NAPALM Playbook
   hosts: all
   connection: local
   gather_facts: False
    
   tasks:
      - napalm_install_config:
          hostname={{ inventory_hostname }}
          username={{ username }}
          dev_os=ios
          password={{ password }}
          config_file=initial.conf
          commit_changes=True
          replace_config=True
          diff_file=initial.diff 
--------------------------------------------------------
Here is my initial.conf. I am trying to config replace with just one cli ( yes with only hostname to see the diff)
$ more initial.conf 
hostname TESTMYSCRIPT

Here is the diff generated. And it is as expected.

$ more initial.diff 
+hostname TESTMYSCRIPT-service timestamps debug datetime msec
-service timestamps log datetime msec
-no service password-encryption
-service counters max age 5
-hostname CAT6KLAB05
-boot-start-marker
-boot-end-marker
--snip----

Thanks for the help.

**Comment by jedelman8** [comment]
When you have replace_config set to True, you should be sending a FULL config file. In your case, you can use a full show run and just change the hostname. Or set replace_config to False and send a partial command list like you are doing.

**Comment by bleishangthem** [comment]
Jason,  Thanks for identifying the mistake. That works.  

Revisited the cisco requirement:
 "When using the configure replace command, you must specify a saved Cisco IOS configuration as the replacement configuration file for the current running configuration. The replacement file must be a complete configuration **generated by a Cisco IOS device** (for example, a configuration generated by the copyrunning-configdestination-url command), or, **if generated externally, the replacement file must comply with the format of files generated by Cisco IOS devices**"

The new playbook
---

 - name: NAPALM Playbook
   hosts: all
   connection: local
   gather_facts: False
    
   tasks:
      - napalm_install_config:
          hostname={{ inventory_hostname }}
          username={{ username }}
          dev_os=ios
          password={{ password }}
          config_file=initial.conf
          commit_changes=True
          replace_config=False
          diff_file=initial.diff 

The config.txt used for merge operation.

TESTMYSCRIPT#more merge_config.txt
hostname TESTMYSCRIPT

**Comment by dbarrosop** [comment]
I think this has been resolved. Otherwise, feel free to reopen.
