### ISSUE TITLE
Probably should raise a warning if provider arguments are unused

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#65]
Like secret...

Or possibly might want to support passing secret in the provider.

**Comment by dbarrosop** [comment]
Yes, well known provider arguments that have a corresponding argument (or even optional_arg) should be mapped accordingly.

**Comment by ktbyers** [comment]
Yes, I misread the code. You can pass everything via the provider including optional_args so I am going to close this.
