### ISSUE TITLE
Mechanism to install modules

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-ansible#67]
@ktbyers I was thinking in a more "pythonic" way of installing these modules. We could have a regular `develop -> master -> release` lifecycle like we have with regular drivers and have the `setup.py` provide a simple cli tool `whereis-napalm-ansible` that returns the path to where the modules where installed so users can add that path to the `ansible.cfg` file.

This would give us a simple mechanism to deploy the modules with all the pip goodies (pin versions, different venv with different versions of the modules, easy rollback if a newer version breaks something, etc).

Thoughts?

**Comment by ktbyers** [comment]
Yes, I like the idea of having a more Pythonic way of installing them (i.e `pip install napalm-ansible`) and having releases with versioning.

I wonder if there is an easier way to do this (i.e. some way to just get them automatically into a default path or just automatically 'echo' the location of the modules and what people need to do at the end of the installation (not sure if we can do this, however, i.e. basically execute a script at end of pip install).

Ansible's docs are poor here...hard to find what exactly the default module search path is? It would be nice to just automatically put them into place Ansible looked automatically (that was per-virtual environment)...but I couldn't find the algorithm Ansible uses for module path determination.

Worse case we can have a post install CLI tool, like you mentioned, that installs them and tells people what to (i.e. add this line to your ansible.cfg which is usually here).

**Comment by dbarrosop** [comment]
Unfortunately I don't think there is any default path other than the folder that comes with ansible itself and installing our code there seems dirty and ugly as that's managed by another package.

**Comment by ktbyers** [comment]
Yes, agreed. Yes, I don't think it makes sense to install it there...to ugly and problem prone. So it sounds like some post install tool is the best we can do.

**Comment by matejv** [comment]
It seems that Ansible recommend distributing modules as part of roles:

http://docs.ansible.com/ansible/playbooks_roles.html#embedding-modules-and-plugins-in-roles

These roles could then be made installable via `ansible-galaxy` command. One downside of this approach is that the user must first call the role with the module in his playbooks, before it's available to other tasks/roles in the playbook.

**Comment by ktbyers** [comment]
Yes, I vote against using Galaxy. I don't think it is net helpful (as far as I can tell).

**Comment by dbarrosop** [comment]
Yeah, I am with ktbyers here. Galaxy provides no value whatsoever and it's just a weird idea. Modules shouldn't be coupled with roles.

**Comment by ktbyers** [comment]
This issue is done.
