### ISSUE TITLE
Instances of '30' in IOS interface description replaced with eight asterisks with napalm_get_facts, interfaces

### ISSUE THREAD

**Issue by mekisiel** [napalm-automation/napalm-ansible#80]
Example output:
ansible_facts:
    interfaces:
        GigabitEthernet0/0:
            description: '>ACC Ethernet AT&T  ********M EDBK6CHS0009< [********000:********000]'
            is_enabled: true
            is_up: true
            last_flapped: -1.0
            mac_address: 24:E9:B3:2E:36:E1
            speed: 100
changed: false
not_implemented: []

Should read:
description: '>ACC Ethernet AT&T  30M EDBK6CHS0009< [30000:30000]'

Versions in use:
ansible 2.3.1.0
napalm (1.2.0)
napalm-base (0.24.1)
napalm-eos (0.6.0)
napalm-fortios (0.4.0)
napalm-ios (0.7.0)
napalm-iosxr (0.5.1)
napalm-junos (0.10.3)
napalm-nxos (0.5.3)
napalm-panos (0.4.0)
napalm-pluribus (0.5.1)
napalm-ros (0.2.2)
napalm-vyos (0.1.3)
netmiko (1.4.1)

**Comment by ktbyers** [comment]
Strange...

Can you show what

`show run int GigabitEthernet0/0` shows from the CLI?

**Comment by mekisiel** [comment]
interface GigabitEthernet0/0
 description >ACC Ethernet AT&T  30M EDBK6CHS0009< [30000:30000]
 no ip address
 no ip redirects
 load-interval 30
 duplex full
 speed 100

**Comment by dbarrosop** [comment]
That looks like ansible's doing. They tend to obfuscate random things they consider "secret". By any chance is your user/password/secret "30" or contains that string?

**Comment by mekisiel** [comment]
Based on David's assumption I looked into the ansible-vault encrypted group_vars file. It turns out that the ios provider information was included in this file with "timeout: 30"

I removed this line, retested, and the value is no longer being obfuscated. Thank you!

**Comment by dbarrosop** [comment]
I'd recommend opening an issue with ansible. The logic they have to obfuscate things is quite silly.

Closing.
