### ISSUE TITLE
setup.x in repo

### ISSUE THREAD

**Issue by itdependsnetworks** [napalm-automation/napalm-ansible#90]
There is a long outstanding issue with ansible with setup.x files and gather_facts. If gather_facts: is not set for False, it will search for any file with setup.x in it under the ansible.cfg library path. This ends up failing for playbooks as there is a name space issue. 

In ntc-modules there has been confusion and issues because of this, and I would recommend to remove the setup.py and setup.cfg file. 

See https://github.com/ansible/ansible/issues/20702 and https://github.com/ansible/ansible/pull/20717 for further details.

**Comment by dbarrosop** [comment]
Ok, I think it makes sense to take this into account. My immediate reaction would be to use a `git submodule` but that has the problem that managing versions requires an extra step but it would allow us to support installing via pip and via "clones".

Any alternative ideas?

**Comment by ktbyers** [comment]
So if we remove the ./library symbolic link wouldn't that fix the issue?

Then people that did `git clone` would have to set the module path to here: 

```
/path/to/napalm-ansible/napalm_ansible
```

And there is no `setup.py` nor `setup.cfg` there.

**Comment by ghost** [comment]
I configure library in ansible.cfg to point to napalm-ansible. This is not in my path.

Got burned with this trying to gather facts on linux box. Removing library config resolved my issue. 

Ansible latches on to the closest `setup.*` it can find. In my case it was the napalm setup.cfg

Can you rename setup.cfg and setup.py in napalm-ansible?

**Comment by ktbyers** [comment]
@bowersjj No, we can't really rename them as those are standard Python files for package creation and package management. 

There might be some complex way we can essentially have two packages.

Why not point ansible library in .ansible.cfg to?

```
/path/to/napalm-ansible/napalm_ansible
```

**Comment by ghost** [comment]
I see my problem.
ansible.cfg pointing to the git clone itself. I never installed. 
It's been so long, I thought I installed via pip along with napalm. 

I should read the README files, and quit wasting other people's time.

**Comment by ktbyers** [comment]
@bowersjj No worries. 

It is an annoying issue...unfortunately, it is a choice of not very good options for what to do about it.

Yes, my .ansible.cfg looks like this:

```
$ cat .ansible.cfg 
[defaults]
hostfile = ~/ansible-hosts
library = ~/napalm-ansible/library:~/ansible-extras/ntc-ansible/library
```

**Comment by ktbyers** [comment]
I don't think we are going to fix this...so I am going to close this issue.
