### ISSUE TITLE
Eliminate os_choices option from napalm-ansible

### ISSUE THREAD

**Issue by targuan** [napalm-automation/napalm-ansible#95]
From #94:
> Allow nxos_ssh to be used

Is there a reason not to rely on napalm get_network_driver and getter exceptions to filter which driver can or can't be used ?
It seems cumbersome to track the drivers for any addition in the implementation when their is already something we can accurately rely on to do so.

**Comment by ktbyers** [comment]
@targuan Yes, agreed...I think choices should just go away and we raise an error if get_network_driver fails.

@dbarrosop Any views on this? I think we talked about this previously IIRC.

**Comment by dbarrosop** [comment]
Agreed.

**Comment by ktbyers** [comment]
Fixed in #132
